### PR TITLE
Initial rebranding and docs.  I have no idea what I'm doing.

### PR DESCRIPTION
**Pull request by N3X15**
## About the PR 

Initial rebranding and docs dickery so there's a line betwixt us and the official SS14 branch.

:cl:
- tweak: We /vg/station now

### CODE REVIEW

**Comment by DorainGrey** [comment]
Should probably update the readme as well, with links to our website etc

**Comment by N3X15** [comment]
> Should probably update the readme as well, with links to our website etc

It was, though?

**Comment by DorainGrey** [comment]
> > Should probably update the readme as well, with links to our website etc
> 
> It was, though?

Disregard, I somehow minimized it.
Sorry

**Comment by adacovsk** [comment]
postin in an ebin bread :P XD

**Pull request merged**
